spring:


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.254.151:3306/user_center?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    username: dogyupi
    password: yupi666

#  设置失效时间为1天
  session:
    timeout: 86400


